### ISSUE TITLE
Kahoot hack and Edpuzzle hack

### ISSUE THREAD

**Issue by pineapplemall** [car-axle-client/community-plugins#3]
Kahoot name bypasser & Edpuzzle mod menu
Devbubba
https://github.com/DevBubba/Bookmarklets/blob/main/Hacks/EDpuzzleModMenu.js https://github.com/DevBubba/Bookmarklets/blob/main/Hacks/KahootNameBypasser.js

**Comment by Penguinify** [comment]
edpuzzle mod menu is the same as the one in car axle client
the repository for kahoot name bypasser says it doesn't work anymore so yh (https://github.com/ThatFruedDued/kahoot-smasher/blob/master/README.md)
